export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  openclawChatEnabled: (process.env.OPENCLAW_CHAT_ENABLED ?? "false").toLowerCase() === "true",
  openclawChatRequired: (process.env.OPENCLAW_CHAT_REQUIRED ?? "false").toLowerCase() === "true",
  openclawChatEndpoint: process.env.OPENCLAW_CHAT_ENDPOINT ?? "",
  openclawChatToken: process.env.OPENCLAW_CHAT_TOKEN ?? "",
  openclawChatTimeoutMs: Number(process.env.OPENCLAW_CHAT_TIMEOUT_MS ?? "25000"),
};
